[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.24'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
via-ir = true

[dependencies]
forge-std = { version = "1.9.4", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_4_25-10-2024_14:36:59_forge-std-1.9.zip" }
"@openzeppelin-contracts" = "5.0.0"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
